### ISSUE TITLE
The template e-mail for Verification via videoconferencing should contain a date before which to organise the meeting

### ISSUE THREAD

**Issue by SergioArbarviro** [michaellaunay/alirpunkto#39]
The [template e-mail for Verification via videoconferencing](https://github.com/michaellaunay/alirpunkto/blob/master/alirpunkto/locale/identity_verification_video_conference_request.pt) should contain a date at the latest when the video conference should take place. This date should be a few days before the deadline for the Veirifiers to vote.

Currently this limit date for the videoconference to take place is replaced by a ### placeholder. This placeholder should be replaced by the code feeding in the deadline for sending data, referred to as {date_send_id_data} in the [KuneAgi code for e-mails](https://gitlab.com/cosmopoliticalcoop/KuneAgi/-/edit/master/novaideo/mail/en.py).

**Comment by michaellaunay** [comment]
It is impossible to know the expiration date of the identity verification via videoconference because we cannot guarantee that the candidate and the verifiers have found a verification date prior to the expiration date. Since AlirPunkto is not copied on the exchanges, it has no way of knowing if the verification date is consistent with the expiration date. Consequently, I propose to suspend the verification via videoconference.
